DROP DATABASE IF EXISTS LOCADORA;
CREATE DATABASE IF NOT EXISTS LOCADORA;
USE LOCADORA;

CREATE TABLE Clientes (
	NomeCliente VARCHAR(40) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	Telefone VARCHAR(11) NOT NULL
);

CREATE TABLE Alugueis (
	Data DATETIME NOT NULL,
	IDCliente INT NOT NULL PRIMARY KEY
);

CREATE TABLE ItensAlugados (
	Comprovante INT NOT NULL PRIMARY KEY,
	IDFilme INT NOT NULL,
	CONSTRAINT FK_IT_FI FOREIGN KEY(IDFilme) REFERENCES Filmes(IDFilme)
);

CREATE TABLE Filmes(
	IDFilme INT NOT NULL PRIMARY KEY,
	Idade TINYINT NOT NULL
);

ALTER TABLE Clientes 
ADD COLUMN IDCliente INT NOT NULL PRIMARY KEY FIRST, 
ADD COLUMN Endereco VARCHAR(150) NOT NULL AFTER NomeCliente;

ALTER TABLE Alugueis
DROP COLUMN IDCliente;

ALTER TABLE Alugueis
ADD COLUMN Comprovante INT NOT NULL PRIMARY KEY FIRST,
ADD COLUMN Devolucao DATETIME NOT NULL AFTER Data,
ADD COLUMN IDCliente INT NOT NULL,
ADD CONSTRAINT FK_ALU_CLI FOREIGN KEY (IDCliente) REFERENCES Clientes (IDCliente);

ALTER TABLE ItensAlugados
DROP COLUMN Comprovante;

ALTER TABLE ItensAlugados
ADD COLUMN QTDEESTOQUE TINYINT NOT NULL,
ADD COLUMN Comprovante INT NOT NULL FIRST,
ADD CONSTRAINT PK_IT PRIMARY KEY (Comprovante, IDFilme);


ALTER TABLE Filmes
ADD COLUMN Titulo VARCHAR(40) NOT NULL,
ADD COLUMN Genero VARCHAR(30) NOT NULL,
ADD COLUMN Idioma VARCHAR(40) NOT NULL,
ADD COLUMN Preco DECIMAL(5,2) NOT NULL,
DROP COLUMN Idade;




